const mongoose = require('mongoose');

exports.CentralizedInverter=mongoose.model('CentralizedInverter',new mongoose.Schema({
    
    timestamp:{type:Date, required:true},
    loggerNo:{type:Number, required:true, min:1, max: 25},
    plantId:{type:Number, required:true, min:1, max: 1000},
    deviceType:{type:Number, required:true, min:51, max: 100},
    deviceNo:{type:Number, required:true, min:0, max: 2500},
    errorFlag:{type:Number, required:true, min:0, max: 1},
    masterFlag:{type:Number, min:0, max: 1},
   
    status:{type:String},
    efficiency:{type:Number, min:0, max: 110},
    temperature:{type:Number, min:-20, max: 120},
    //transformerTemperature:{type:Number, min:-20, max: 120},
    IGBTATemperature:{type:Number, min:-20, max: 120},
    IGBTBTemperature:{type:Number, min:-20, max: 120},
    IGBTCTemperature:{type:Number, min:-20, max: 120},
    voltagePhaseR:{type:Number, min:0, max: 600},
    voltagePhaseY:{type:Number, min:0, max: 600},
    voltagePhaseB:{type:Number, min:0, max: 600},
    outputVoltage:{type:Number},
    currentPhaseR:{type:Number},
    currentPhaseY:{type:Number},
    currentPhaseB:{type:Number},
    outputCurrent:{type:Number},
    powerPhaseR:{type:Number},
    powerPhaseY:{type:Number},
    powerPhaseB:{type:Number},
    activePower:{type:Number},
    reactivePower:{type:Number},
    apparantPower:{type:Number},
    powerFactor:{type:Number},
    frequency:{type:Number},
    voltageUnit1:{type:Number},
    voltageUnit2:{type:Number},
    voltageUnit3:{type:Number},
    voltageUnit4:{type:Number},
    voltageUnit5:{type:Number},
    voltageUnit6:{type:Number},
    voltageUnit7:{type:Number},
    voltageUnit8:{type:Number},
    voltageUnit9:{type:Number},
    voltageUnit10:{type:Number},
    voltageUnit11:{type:Number},
    voltageUnit12:{type:Number},
    currentUnit1:{type:Number},
    currentUnit2:{type:Number},
    currentUnit3:{type:Number},
    currentUnit4:{type:Number},
    currentUnit5:{type:Number},
    currentUnit6:{type:Number},
    currentUnit7:{type:Number},
    currentUnit8:{type:Number},
    currentUnit9:{type:Number},
    currentUnit10:{type:Number},
    currentUnit11:{type:Number},
    currentUnit12:{type:Number},
    powerUnit1:{type:Number},
    powerUnit2:{type:Number},
    powerUnit3:{type:Number},
    powerUnit4:{type:Number},
    powerUnit5:{type:Number},
    powerUnit6:{type:Number},
    powerUnit7:{type:Number},
    powerUnit8:{type:Number},
    powerUnit9:{type:Number},
    powerUnit10:{type:Number},
    powerUnit11:{type:Number},
    powerUnit12:{type:Number},
    currentInput1:{type:Number},
    currentInput2:{type:Number},
    currentInput3:{type:Number},
    currentInput4:{type:Number},
    currentInput5:{type:Number},
    currentInput6:{type:Number},
    currentInput7:{type:Number},
    currentInput8:{type:Number},
    currentInput9:{type:Number},
    currentInput10:{type:Number},
    currentInput11:{type:Number},
    currentInput12:{type:Number},
    currentInput13:{type:Number},
    currentInput14:{type:Number},
    currentInput15:{type:Number},
    currentInput16:{type:Number},
    currentInput17:{type:Number},
    currentInput18:{type:Number},
    currentInput19:{type:Number},
    currentInput20:{type:Number},
    currentInput21:{type:Number},
    currentInput22:{type:Number},
    currentInput23:{type:Number},
    currentInput24:{type:Number},
    currentInput25:{type:Number},
    currentInput26:{type:Number},
    currentInput27:{type:Number},
    currentInput28:{type:Number},
    currentInput29:{type:Number},
    currentInput30:{type:Number},
    inputVoltage:{type:Number},
    inputCurrent:{type:Number},
    inputPower:{type:Number},
    dailyEnergy:{type:Number, min:0, max: 25000},
    totalEnergy:{type:Number},
    dailyRuntime:{type:Number},
    totalRuntime:{type:Number},
    gridConnectionTime:{type:Number},
    error:{type:String},
    warning:{type:String},
    fault:{type:String},
    breakerStatus:{type:String}
}));
