const mongoose = require('mongoose');

exports.SCB=mongoose.model('SCB',new mongoose.Schema({
    timestamp:{type:Date, required:true},
    loggerNo:{type:Number, required:true, min:1, max: 25},
    plantId:{type:Number, required:true, min:1, max: 1000},
    deviceType:{type:Number, required:true, min:201, max: 225},
    deviceNo:{type:Number, required:true, min:0, max: 100},
    errorFlag:{type:Number, required:true, min:0, max: 1},
  
    status:{type:String},
    temperature:{type:Number, min:-20, max: 100},
    temperature1:{type:Number, min:-20, max: 100},
    temperature2:{type:Number, min:-20, max: 100},
    voltage:{type:Number},
    current:{type:Number},
    power:{type:Number},
    currentString1:{type:Number},
    currentString2:{type:Number},
    currentString3:{type:Number},
    currentString4:{type:Number},
    currentString5:{type:Number},
    currentString6:{type:Number},
    currentString7:{type:Number},
    currentString8:{type:Number},
    currentString9:{type:Number},
    currentString10:{type:Number},
    currentString11:{type:Number},
    currentString12:{type:Number},
    currentString13:{type:Number},
    currentString14:{type:Number},
    currentString15:{type:Number},
    currentString16:{type:Number},
    currentString17:{type:Number},
    currentString18:{type:Number},
    currentString19:{type:Number},
    currentString20:{type:Number},
    currentString21:{type:Number},
    currentString22:{type:Number},
    currentString23:{type:Number},
    currentString24:{type:Number},
    error:{type:String},
    warning:{type:String},
    fault:{type:String}
}));