const mongoose = require('mongoose');

exports.StringInverter=mongoose.model('StringInverter',new mongoose.Schema({
    timestamp:{type:Date, required:true},
    loggerNo:{type:Number, required:true, min:1, max: 25},
    plantId:{type:Number, required:true, min:1, max: 1000},
    deviceType:{type:Number, required:true, min:1, max: 50},
    deviceNo:{type:Number, required:true, min:0, max: 100},
    errorFlag:{type:Number, required:true, min:0, max: 1},
  
    status:{type:String},
    temperature:{type:Number, min:-20, max: 120},
    voltagePhaseR:{type:Number, min:0, max: 1000},
    voltagePhaseY:{type:Number, min:0, max: 1000},
    voltagePhaseB:{type:Number, min:0, max: 1000},
    outputVoltage:{type:Number},
    currentPhaseR:{type:Number},
    currentPhaseY:{type:Number},
    currentPhaseB:{type:Number},
    outputCurrent:{type:Number},
    powerPhaseR:{type:Number},
    powerPhaseY:{type:Number},
    powerPhaseB:{type:Number},
    activePower:{type:Number},
    reactivePower:{type:Number},
    apparentPower:{type:Number},
    powerFactor:{type:Number},
    frequency:{type:Number},
    voltageMPPT1:{type:Number},
    voltageMPPT2:{type:Number},
    voltageMPPT3:{type:Number},
    voltageMPPT4:{type:Number},
    voltageMPPT5:{type:Number},
    voltageMPPT6:{type:Number},
    voltageMPPT7:{type:Number},
    voltageMPPT8:{type:Number},
    voltageMPPT9:{type:Number},
    voltageMPPT10:{type:Number},
    voltageMPPT11:{type:Number},
    voltageMPPT12:{type:Number},
    voltageMPPT13:{type:Number},
    voltageMPPT14:{type:Number},
    voltageMPPT15:{type:Number},
    currentMPPT1:{type:Number},
    currentMPPT2:{type:Number},
    currentMPPT3:{type:Number},
    currentMPPT4:{type:Number},
    currentMPPT5:{type:Number},
    currentMPPT6:{type:Number},
    currentMPPT7:{type:Number},
    currentMPPT8:{type:Number},
    currentMPPT9:{type:Number},
    currentMPPT10:{type:Number},
    currentMPPT11:{type:Number},
    currentMPPT12:{type:Number},
    currentMPPT13:{type:Number},
    currentMPPT14:{type:Number},
    currentMPPT15:{type:Number},
    powerMPPT1:{type:Number},
    powerMPPT2:{type:Number},
    powerMPPT3:{type:Number},
    powerMPPT4:{type:Number},
    powerMPPT5:{type:Number},
    powerMPPT6:{type:Number},
    powerMPPT7:{type:Number},
    powerMPPT8:{type:Number},
    powerMPPT9:{type:Number},
    powerMPPT10:{type:Number},
    powerMPPT11:{type:Number},
    powerMPPT12:{type:Number},
    powerMPPT13:{type:Number},
    powerMPPT14:{type:Number},
    powerMPPT15:{type:Number},
    inputVoltage:{type:Number},
    inputCurrent:{type:Number},
    inputPower:{type:Number},
    currentString1:{type:Number},
    currentString2:{type:Number},
    currentString3:{type:Number},
    currentString4:{type:Number},
    currentString5:{type:Number},
    currentString6:{type:Number},
    currentString7:{type:Number},
    currentString8:{type:Number},
    currentString9:{type:Number},
    currentString10:{type:Number},
    currentString11:{type:Number},
    currentString12:{type:Number},
    currentString13:{type:Number},
    currentString14:{type:Number},
    currentString15:{type:Number},
    currentString16:{type:Number},
    currentString17:{type:Number},
    currentString18:{type:Number},
    currentString19:{type:Number},
    currentString20:{type:Number},
    currentString21:{type:Number},
    currentString22:{type:Number},
    currentString23:{type:Number},
    currentString24:{type:Number},
    currentString25:{type:Number},
    currentString26:{type:Number},
    currentString27:{type:Number},
    currentString28:{type:Number},
    currentString29:{type:Number},
    currentString30:{type:Number},
    efficiency:{type:Number, min:0, max: 110},
    dailyEnergy:{type:Number, min:0, max: 2000},
    totalEnergy:{type:Number},
    dailyRuntime:{type:Number},
    totalRuntime:{type:Number},
    //deratingPercent:{type:Number},
    error:{type:String},
    warning:{type:String},
    fault:{type:String}
}));